maven-cache-server:
  baseFolderToStore: ./
  storeType: FILE_SYSTEM
aws:
  accessKeyId:
  secretAccessKey:
  region:

authentication:
  enabled: true

spring:
  security:
    user:
      name: ${authentication.user.name:admin}
      password: ${authentication.user.password:admin}
