version: "3.8"
services:
  maven-cache-server:
    image: ghcr.io/cenkakin/maven-cache-server:latest
    ports:
      - "8080:8080"
    environment:
      authentication.enabled: true
      authentication.user.name: admin
      authentication.user.password: admin
      maven-cache-server.storeType: S3
      maven-cache-server.baseFolderToStore: YOUR_BUCKET_PATH
      aws.accessKeyId: YOUR_ACCESS_KEY
      aws.secretAccessKey: YOUR_SECRET_KEY
      aws.region: YOUR_REGION
